[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "nestar"
version = "0.1.0"
description = "Nested Sampling for ARIMA Model Selection in Astronomical Time-Series Analysis"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "jax",
    "blackjax @ git+https://github.com/handley-lab/blackjax.git@95e93ed93e726b95143b2f4a9582888621625f52",
    "anesthetic",
    "tqdm",
    "fgivenx",
    "statsmodels",
    "pmdarima"
]

[project.optional-dependencies]
notebook = [
    "ipywidgets",
]

[tool.setuptools.packages.find]
where = ["src"]